### ISSUE TITLE
training code?

### ISSUE THREAD

**Issue by anewusername77** [bbbolt/MDRN#1]
thank you for your great work! 
is it possible to release your training code?

**Comment by bbbolt** [comment]
目前还在整理中, 我们会尽快

**Comment by bbbolt** [comment]
m

> 感谢你杰出的工作！ 可以发布一下你的训练代码吗？

感谢您对我们工作的关注, 目前训练文件还在整理当中,我们会尽快完成

**Comment by bbbolt** [comment]
> thank you for your great work! is it possible to release your training code?
您好，训练细节已上传，感谢您的关注！

**Comment by anewusername77** [comment]
thanks
