### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tojeteter** [bbbolt/MDRN#2]
I noticed that this repository doesn't have a specified license. Could you please clarify how this code is licensed?

**Comment by bbbolt** [comment]
We apologize for not explicitly specifying the license earlier. We have now decided to use the MIT license. The MIT license is a permissive open-source license that allows others to freely use, modify, and distribute our code. Thank you for your attention and reminder. We will promptly add the MIT license to the project and update the relevant information. We greatly appreciate your support!




---Original---
From: ***@***.***&gt;
Date: Fri, Oct 6, 2023 17:23 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [bbbolt/MDRN] License (Issue #2)




 
I noticed that this repository doesn't have a specified license. Could you please clarify how this code is licensed?

**Comment by tojeteter** [comment]
Thanks for the quick response and for choosing the MIT license for your project.
